### ISSUE TITLE
Build Error when I try aemm build ios --device

### ISSUE THREAD

**Issue by ilitotor** [adobe-marketing-cloud-mobile/aemm-ios#6]
I cant build an iOS project.

Always I get this error:

> Check dependencies
> Code Signing Error: No certificate matching 'Don't Code Sign' found:  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.
> 
> ** BUILD FAILED **
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> Error: Error code 65 for command: xcodebuild with args: -xcconfig,xxx/platforms/ios/cordova/build-debug.xcconfig,-project,CordovaPlugins.xcodeproj,ARCHS=armv7 arm64,-target,CordovaPlugins,-configuration,Debug,-sdk,iphoneos,build,VALID_ARCHS=armv7 arm64,CONFIGURATION_BUILD_DIR= xxx/platforms/ios/build/device,SHARED_PRECOMPS_DIR=xxx/platforms/ios/build/sharedpch

I tried to use:

>  sudo /usr/libexec/PlistBuddy -c "Set DefaultProperties:CODE_SIGNING_REQUIRED NO" "$(xcode-select -p)/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/SDKSettings.plist"

But, apparently, this command that's not for this.

In other Mac works well, but just in my Mac don't work.

I have a XCode 9.3 and nodejs 8.11.1

Thanks.

**Comment by jeevan-raj** [comment]
Hi,

Did you resolve this issue?

Regards,
Jeevan

**Comment by jeevan-raj** [comment]
@ilitotor How did you manage to resolve this issue?

Thanks in advance
